# backend/courses/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import CourseViewSet, VideoViewSet

# Create a router instance
router = DefaultRouter()
# Register our viewsets with the router, specifying a basename
router.register(r'courses', CourseViewSet, basename='course')
router.register(r'videos', VideoViewSet, basename='video')

urlpatterns = [
    # This single path will serve all the URLs generated by the router
    path('', include(router.urls)),
]