# Generated by Django 5.2.4 on 2025-08-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='segments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
