# Generated by Django 5.2.4 on 2025-10-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='temp_field',
            field=models.CharField(default='', max_length=1),
        ),
    ]
