# Generated by Django 5.2.4 on 2025-10-15 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_duration_hours_course_is_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(0.1, 0.1), (0.6, 0.6), (1.1, 1.1), (1.6, 1.6), (2.1, 2.1), (2.6, 2.6), (3.1, 3.1), (3.6, 3.6), (4.1, 4.1), (4.6, 4.6)], decimal_places=1, default=5.0, max_digits=2)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='Course Reviewed')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_left', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
