# Generated by Django 5.2.4 on 2025-10-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quiz_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='temp_field',
        ),
    ]
