# Generated by Django 5.2.4 on 2025-08-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='segment_end_time',
            field=models.FloatField(default=0.0, help_text='The timestamp in seconds when this quiz should appear.'),
        ),
    ]
