# Generated by Django 5.2.4 on 2025-10-16 05:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(choices=[(Decimal('0.5'), '0.5'), (Decimal('1'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5'), '5.0')], decimal_places=1, default=Decimal('5.0'), max_digits=2),
        ),
    ]
