# Generated by Django 5.2.4 on 2025-08-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_quiz_segment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='segment_start_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='segment_end_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='segment_index',
            field=models.IntegerField(default=0),
        ),
    ]
