# Generated by Django 5.2.4 on 2025-08-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_quiz_segment_start_time_alter_quiz_segment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='segment_start_time',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='segment_end_time',
            field=models.FloatField(default=0.0, help_text='The timestamp in seconds when this quiz should appear.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='segment_index',
            field=models.IntegerField(help_text='The index of the video segment this quiz is for.'),
        ),
    ]
