# Generated by Django 5.2.4 on 2025-10-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, help_text='What will you learn in this course?', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='outcome',
            field=models.TextField(blank=True, help_text='Expected outcome after completing this course.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='skills_gained',
            field=models.TextField(blank=True, help_text='Skills you’ll gain from this course.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.FloatField(default=0),
        ),
    ]
