# Generated by Django 5.2.4 on 2025-08-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_quiz_segment_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
