# Generated by Django 5.2.4 on 2025-10-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_studentquiz_studentquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquestion',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='studentquiz',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentquiz',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentquiz',
            name='video',
        ),
        migrations.DeleteModel(
            name='QuizGenerationLog',
        ),
        migrations.DeleteModel(
            name='StudentQuestion',
        ),
        migrations.DeleteModel(
            name='StudentQuiz',
        ),
    ]
