# Generated by Django 5.2.4 on 2025-10-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_studentquestion_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='notes_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
