# Generated by Django 5.2.4 on 2025-09-15 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_video_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='video',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='segments',
        ),
        migrations.RemoveField(
            model_name='video',
            name='transcript',
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
