# Generated by Django 5.2.4 on 2025-09-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_video_options_remove_video_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
