# Generated by Django 5.2.4 on 2025-10-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_studentprogress_notes_unlocked_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProgress',
        ),
    ]
