# Generated by Django 5.2.4 on 2025-10-22 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_studentprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprogress',
            options={'verbose_name_plural': 'Student Progress'},
        ),
        migrations.RenameField(
            model_name='studentprogress',
            old_name='all_quizzes_passed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='notes_unlocked',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='video_completed',
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='quizzes_passed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='segments',
            field=models.JSONField(blank=True, default=list, help_text='List of video segments (time, index, text)', null=True),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprogress',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.video'),
        ),
    ]
