# Generated by Django 5.2.4 on 2025-10-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_studentprogress_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprogress',
            old_name='is_completed',
            new_name='all_quizzes_passed',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='quizzes_passed_count',
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='video_completed',
            field=models.BooleanField(default=False),
        ),
    ]
